[package]
name = "crates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[lib]
name = "crates_lib"
path = "src/lib.rs"

[[bin]]
name = "crates_bin"
path = "src/main.rs"
